//Auth

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';

//Places

export const PLACES_AUTOCOMPLETE_REQUEST = 'PLACES_AUTOCOMPLETE_REQUEST';
export const PLACES_AUTOCOMPLETE_SUCCESS = 'PLACES_AUTOCOMPLETE_SUCCESS';
export const PLACES_AUTOCOMPLETE_FAILURE = 'PLACES_AUTOCOMPLETE_FAILURE';
